/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThingIdRouteImport } from './routes/thing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingIdRoute = ThingIdRouteImport.update({
  id: '/thing/$id',
  path: '/thing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/download': typeof DownloadRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/thing/$id': typeof ThingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/download': typeof DownloadRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/thing/$id': typeof ThingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/download': typeof DownloadRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/thing/$id': typeof ThingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/download'
    | '/inbox'
    | '/library'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/thing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/download'
    | '/inbox'
    | '/library'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/thing/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/download'
    | '/inbox'
    | '/library'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/thing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DownloadRoute: typeof DownloadRoute
  InboxRoute: typeof InboxRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ThingIdRoute: typeof ThingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thing/$id': {
      id: '/thing/$id'
      path: '/thing/$id'
      fullPath: '/thing/$id'
      preLoaderRoute: typeof ThingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DownloadRoute: DownloadRoute,
  InboxRoute: InboxRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ThingIdRoute: ThingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
